name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Make slug values available
        uses: gacts/github-slug@v1
        id: slug

      - name: Build the file
        run: |
          cd /home/runner/work/clock-weather-card/clock-weather-card
          yarn install
          yarn version --no-git-tag-version --new-version ${{ steps.slug.outputs.version }}
          yarn build

      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v1-release

        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /home/runner/work/clock-weather-card/clock-weather-card/dist/clock-weather-card.js
          asset_name: clock-weather-card.js
          tag: ${{ github.ref }}
          overwrite: true
